name: CI - PulseChat

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: pulsechatdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal

    - name: Publish API
      run: dotnet publish PulseChat.API/PulseChat.API.csproj -c Release -o out

    - name: Build Docker Image
      run: docker build -t pulsechat-api -f PulseChat.API/Dockerfile .

