version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: pulsechatdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  pulsechat-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5130:80"
    depends_on:
      - postgres
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=pulsechatdb;Username=postgres;Password=1
      - ConnectionStrings__Redis=redis:6379
    volumes:
      - ./PulseChat.API/wwwroot:/app/wwwroot

volumes:
  pgdata:
